name: Deploy to S3
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Install Dependencies
        uses: npm install
      - name: Build App
        uses: npm run build
      - name: Configure AWS Credentails
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Deploy to S3
        run: aws s3 sync build/ s3://my-first-bucket-nabeel-tahir
      - name: Enable Website Hosting
        run: aws s3 website s3://my-first-bucket-nabeel-tahir --index-document index.html --error-document index.html
      - name: Get Bucket URL
        id: bucket_url
        run: echo ::set-output name=url::$(aws s3 presign s3://my-first-bucket-nabeel-tahir/index.html)
      - name: Open app in browser
        run: | 
          echo "App URL: ${{ steps.bucket_url.outputs.url }}"
          xdg-open ${{ steps.bucket_url.outputs.url }}